/**
 * URL state. The month and the selected reservation live in the query string
 * (`/schedule?m=2026-10&r=r_ab12cd34`), so every view is a link: shareable, back-button
 * friendly, and rendered on the server with no client state.
 */
import { addMonths, isISODate, isYearMonth, yearMonthOf, type ISODate, type YearMonth } from "../domain/dates";

/** How far ahead the schedule can be browsed and booked. */
export const MONTHS_AHEAD = 24;

export type SearchParams = Record<string, string | string[] | undefined>;

export const firstParam = (value: string | string[] | undefined): string | undefined => (Array.isArray(value) ? value[0] : value);

export const lastAllowedMonth = (today: ISODate): YearMonth => addMonths(yearMonthOf(today), MONTHS_AHEAD);

/** A valid month from `?m=`, clamped to [first, last]; null when absent or malformed so the caller can default to this month. */
export function parseMonthParam(value: string | string[] | undefined, first: YearMonth, last: YearMonth): YearMonth | null {
  const m = firstParam(value);
  if (!isYearMonth(m)) return null;
  return m < first ? first : m > last ? last : m;
}

export function parseDateParam(value: string | string[] | undefined): ISODate | null {
  const d = firstParam(value);
  return isISODate(d) ? d : null;
}

/** Ids are generated by us: letters, digits, `_` and `-` only. */
export function parseIdParam(value: string | string[] | undefined): string | null {
  const id = firstParam(value);
  return id && /^[A-Za-z0-9_-]{1,80}$/.test(id) ? id : null;
}

export type ScheduleOpts = { showCancelled?: boolean; flash?: "booked" | "saved" };

export function scheduleHref(month: YearMonth, reservationId?: string | null, opts: ScheduleOpts = {}): string {
  const query = new URLSearchParams({ m: month });
  if (reservationId) query.set("r", reservationId);
  if (opts.showCancelled) query.set("cancelled", "1");
  if (opts.flash) query.set("flash", opts.flash);
  return `/schedule?${query.toString()}`;
}

export function newReservationHref(prefill: { berthId?: string; start?: ISODate; end?: ISODate } = {}): string {
  const query = new URLSearchParams();
  if (prefill.berthId) query.set("berth", prefill.berthId);
  if (prefill.start) query.set("start", prefill.start);
  if (prefill.end) query.set("end", prefill.end);
  const qs = query.toString();
  return qs ? `/reservations/new?${qs}` : "/reservations/new";
}

export const editReservationHref = (id: string): string => `/reservations/${encodeURIComponent(id)}/edit`;

export const vesselsHref = (q?: string): string => (q ? `/vessels?${new URLSearchParams({ q }).toString()}` : "/vessels");
