/**
 * URL state for the schedule. The month and the selected reservation live in the
 * query string (`/schedule?m=2019-07&r=r_ab12cd34ef`) so every view is a link:
 * shareable, back-button friendly, and rendered on the server with no client state.
 */
import { addMonths, isISODate, isYearMonth, yearMonthOf, type ISODate, type YearMonth } from "../domain/dates";

/** The archive starts in August 1997; planning runs two years past today. */
export const FIRST_MONTH: YearMonth = "1997-01";
export const MONTHS_AHEAD = 24;

export type SearchParams = Record<string, string | string[] | undefined>;

export const firstParam = (value: string | string[] | undefined): string | undefined =>
  Array.isArray(value) ? value[0] : value;

export function lastAllowedMonth(today: ISODate): YearMonth {
  return addMonths(yearMonthOf(today), MONTHS_AHEAD);
}

/** A valid, in-range month from `?m=`, or null so the caller can fall back to the default month. */
export function parseMonthParam(value: string | string[] | undefined, today: ISODate): YearMonth | null {
  const m = firstParam(value);
  if (!isYearMonth(m)) return null;
  if (m < FIRST_MONTH) return FIRST_MONTH;
  const last = lastAllowedMonth(today);
  return m > last ? last : m;
}

export function parseDateParam(value: string | string[] | undefined): ISODate | null {
  const d = firstParam(value);
  return isISODate(d) ? d : null;
}

/** Reservation and vessel ids are generated by us: letters, digits, `_` and `-` only. */
export function parseIdParam(value: string | string[] | undefined): string | null {
  const id = firstParam(value);
  return id && /^[A-Za-z0-9_-]{1,80}$/.test(id) ? id : null;
}

export function scheduleHref(month: YearMonth, reservationId?: string | null, opts: { showCancelled?: boolean } = {}): string {
  const query = new URLSearchParams({ m: month });
  if (reservationId) query.set("r", reservationId);
  if (opts.showCancelled) query.set("cancelled", "1");
  return `/schedule?${query.toString()}`;
}

export const editReservationHref = (id: string): string => `/reservations/${encodeURIComponent(id)}/edit`;

export const vesselsHref = (opts: { q?: string; status?: string } = {}): string => {
  const query = new URLSearchParams();
  if (opts.q) query.set("q", opts.q);
  if (opts.status) query.set("status", opts.status);
  const qs = query.toString();
  return qs ? `/vessels?${qs}` : "/vessels";
};

export function newReservationHref(prefill: { berthId?: string; start?: ISODate; end?: ISODate } = {}): string {
  const query = new URLSearchParams();
  if (prefill.berthId) query.set("berth", prefill.berthId);
  if (prefill.start) query.set("start", prefill.start);
  if (prefill.end) query.set("end", prefill.end);
  const qs = query.toString();
  return qs ? `/reservations/new?${qs}` : "/reservations/new";
}
